LMT.Web.Application/Controllers/ComponentGroupsController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web.Mvc;
using LMT.Data.EF;
using LMT.Web.Application.Models;
using MvcContrib.Pagination;

namespace LMT.Web.Application.Controllers
{
    [Authorize]
    public class ComponentGroupsController : Controller
    {
        private readonly Entities _entities;

        public ComponentGroupsController(Entities entities)
        {
            _entities = entities;
        }

        public ActionResult Index(int? page)
        {
            var models =                            
                _entities.ComponentGroups.Where(c => !c.Deleted).Include(c => c.ComponentGroupComponents)
                    .OrderByDescending(c => c.UpdatedOn)
                    .Select(
                        c =>
                            new ComponentGroupReadModel
                            {
                                Id = c.Id,
                                Name = c.Name,
                                ComponentGroupComponents = c.ComponentGroupComponents
                            });

            ViewBag.AjaxEnabled = true;

            return View(models.AsPagination(page ?? 1, 15));
        }

        public ActionResult Create()
        {
            return View(new ComponentGroupCreateModel());
        }

        public ActionResult Edit(int id)
        {
            var componentGroup = _entities.ComponentGroups.Find(id);

            var components = _entities.Components.Where(c => !c.Deleted).ToList();

            var model = new ComponentGroupEditModel
            {
                Id = componentGroup.Id,
                Name = componentGroup.Name,
                ComponentGroupComponentModels =
                    componentGroup.ComponentGroupComponents.Select(
                        c => new ComponentGroupComponentModel
                        {
                            Quantity = c.Quantity.ToString("0.#"),
                            ComponentId = c.Component.Id,
                            Name = c.Component.Name,
                            Sku = c.Component.Sku
                        }).ToList(),
                Components =
                    components.OrderBy(c => c.Sku).Select(
                        c =>
                            new SelectListItem
                            {
                                Text = string.Format("{0}({1})", c.Sku, c.Name),
                                Value = c.Id.ToString()
                            })
            };

            ViewBag.AjaxEnabled = true;

            return View("Edit", model);
        }

        public PartialViewResult DeleteConfirm(int id)
        {
            var componentGroup = _entities.ComponentGroups.Find(id);
            
            ViewBag.Id = componentGroup.Id;
            ViewBag.ComponentGroupName = componentGroup.Name;

            return PartialView("_DeleteConfirm");
        }

        public ActionResult CheckAvailability()
        {
            ViewBag.AjaxEnabled = true;

            return View();
        }
        
        public JsonResult GetComponentGroups()
        {
            var components =
                _entities.ComponentGroups.Where(c => !c.Deleted)
                    .OrderBy(c => c.Name).ToList()
                    .Select(
                        c =>
                            new
                            {
                                value = c.Id,
                                text = string.Format("{0}({1} componenti)", c.Name, c.ComponentGroupComponents.Count())
                            }).ToList();

            return Json(components, JsonRequestBehavior.AllowGet);
        }

        public JsonResult CalculateAvailability(IEnumerable<ComponentGroupQuantityModel> componentGroupQuantityModels)
        {
            var componentGroupIds = componentGroupQuantityModels.Select(c => c.SelectedComponentGroupId).ToList();

            var componentGroups =
                _entities.ComponentGroups.Where(c => componentGroupIds.Contains(c.Id))
                    .Include(c => c.ComponentGroupComponents)
                    .ToList();

            var components =
                componentGroups.SelectMany(c => c.ComponentGroupComponents).Select(c => c.Component).Distinct();

            var componentsAvailability =
                components.Select(c => new {c.Id, c.Name, c.Sku, c.StockQuantity}).OrderBy(c => c.Sku)
                    .ToList();

            var componentsQuantityNeeded = new Dictionary<Component, decimal>();
            var componentsQuantityRemaining = new Dictionary<Component, decimal>();

            foreach (var componentGroup in componentGroups)
            {
                foreach (var componentGroupComponent in componentGroup.ComponentGroupComponents)
                {
                    var numberOfComponentGroupToBeAssembled =
                        componentGroupQuantityModels.First(c => c.SelectedComponentGroupId == componentGroup.Id)
                            .Quantity;

                    if (!componentsQuantityNeeded.ContainsKey(componentGroupComponent.Component))
                        componentsQuantityNeeded.Add(componentGroupComponent.Component, 0);

                    componentsQuantityNeeded[componentGroupComponent.Component] += componentGroupComponent.Quantity*
                                                                             numberOfComponentGroupToBeAssembled;
                }
            }

            foreach (var keyValue in componentsQuantityNeeded)
            {
                var componentCurrentQuantity = componentsAvailability.First(c => c.Id == keyValue.Key.Id).StockQuantity;

                componentsQuantityRemaining.Add(keyValue.Key, componentCurrentQuantity - keyValue.Value);
            }

            var componentsQuantityNeededModel =
                componentsQuantityNeeded.Select(c => new {c.Key.Id, c.Key.Name, c.Key.Sku, StockQuantity = c.Value})
                    .OrderBy(c => c.Sku);

            var componentsQuantityRemainingModel =
                componentsQuantityRemaining.Select(c => new {c.Key.Id, c.Key.Name, c.Key.Sku, StockQuantity = c.Value})
                    .OrderBy(c => c.Sku);

            return
                Json(
                    new
                    {
                        componentsAvailability,
                        componentsNeedAvailability = componentsQuantityNeededModel,
                        componentsRemainingAvailability = componentsQuantityRemainingModel
                    });
        }

        public PartialViewResult RemoveComponentQuantities()
        {
            return PartialView("_RemoveQuantitiesConfirm");
        }
        
        [HttpPost]
        public ActionResult RemoveComponentQuantities(IEnumerable<ComponentGroupQuantityModel> componentGroupQuantityModels)
        {
            var componentGroupIds = componentGroupQuantityModels.Select(c => c.SelectedComponentGroupId).ToList();

            var componentGroups =
                _entities.ComponentGroups.Where(c => componentGroupIds.Contains(c.Id))
                    .Include(c => c.ComponentGroupComponents)
                    .ToList();

            var componentsQuantityNeeded = new Dictionary<Component, decimal>();            

            foreach (var componentGroup in componentGroups)
            {
                foreach (var componentGroupComponent in componentGroup.ComponentGroupComponents)
                {
                    var numberOfComponentGroupToBeAssembled =
                        componentGroupQuantityModels.First(c => c.SelectedComponentGroupId == componentGroup.Id)
                            .Quantity;

                    if (!componentsQuantityNeeded.ContainsKey(componentGroupComponent.Component))
                        componentsQuantityNeeded.Add(componentGroupComponent.Component, 0);

                    componentsQuantityNeeded[componentGroupComponent.Component] += componentGroupComponent.Quantity *
                                                                             numberOfComponentGroupToBeAssembled;
                }
            }

            foreach (var keyValue in componentsQuantityNeeded)
            {                
                keyValue.Key.StockQuantity -= keyValue.Value;
                keyValue.Key.UpdatedOn = DateTime.Now;

                var componentEntry = new ComponentEntry
                {
                    Component = keyValue.Key,
                    CreatedOn = DateTime.Now,
                    Quantity = keyValue.Value*-1,
                    Note = ""
                };

                _entities.ComponentEntries.Add(componentEntry);
            }

            _entities.SaveChanges();

            return Json(null);
        }        

        [HttpPost]
        public ActionResult Delete(int id)
        {
            var componentGroup = _entities.ComponentGroups.Find(id);

            componentGroup.Deleted = true;

            _entities.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Create(ComponentGroupCreateModel componentGroupCreateModel)
        {
            var componentGroup = new ComponentGroup
            {
                Name = componentGroupCreateModel.Name,
                CreatedOn = DateTime.Now,
                UpdatedOn = DateTime.Now
            };

            _entities.ComponentGroups.Add(componentGroup);

            _entities.SaveChanges();

            return RedirectToAction("Edit", new { id = componentGroup.Id });
        }

        [HttpPost]
        public ActionResult Edit(ComponentGroupEditModel componentGroupEditModel)
        {
            var componentGroup = _entities.ComponentGroups.Find(componentGroupEditModel.Id);

            componentGroup.Name = componentGroupEditModel.Name;

            var components =
                componentGroupEditModel.ComponentGroupComponentModels.Where(

LMT.Web.Application/Controllers/ComponentsController.cs
using System;
using System.Data.Entity;
using System.Globalization;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using ClosedXML.Excel;
using LMT.Data.EF;
using LMT.Web.Application.Models;
using LMT.Web.Application.Properties;
using MvcContrib.Pagination;

namespace LMT.Web.Application.Controllers
{
    [Authorize]
    public class ComponentsController : Controller
    {
        private readonly Entities _entities;

        public ComponentsController(Entities entities)
        {
            _entities = entities;
        }

        public ActionResult Index(int? page, ComponentSearchModel componentSearchModel)
        {
            var components = _entities.Components.Where(c => !c.Deleted);

            if (!string.IsNullOrWhiteSpace(componentSearchModel.Name))
                components = components.Where(c => c.Name.Contains(componentSearchModel.Name));
            
            if (!string.IsNullOrWhiteSpace(componentSearchModel.Sku))
                components = components.Where(c => c.Sku.Contains(componentSearchModel.Sku));

            componentSearchModel.SearchResultModels =
                components.OrderByDescending(c => c.UpdatedOn).ToList().Select(
                    c =>
                        new ComponentReadModel
                        {
                            Id = c.Id,
                            Name = c.Name,
                            Sku = c.Sku,
                            StockQuantity = c.StockQuantity.ToString()
                        });

            componentSearchModel.ComponentGroupReadModels =
                _entities.ComponentGroups.Where(c => !c.Deleted).Include(c => c.ComponentGroupComponents)
                    .OrderByDescending(c => c.UpdatedOn)
                    .Select(
                        c =>
                            new ComponentGroupReadModel
                            {
                                Id = c.Id,
                                Name = c.Name,
                                ComponentGroupComponents = c.ComponentGroupComponents
                            });

            componentSearchModel.SearchResultModels = componentSearchModel.SearchResultModels.AsPagination(page ?? 1, 15);

            ViewBag.AjaxEnabled = true;

            return View(componentSearchModel);
        }

        public FileContentResult Export(ComponentSearchModel componentSearchModel)
        {
            var workbook = new XLWorkbook();
            var workSheet = workbook.AddWorksheet("Componenti");

            workSheet.Column("1").Hide();
            workSheet.Cell("A1").Value = "Id";
            workSheet.Cell("B1").Value = "Codice";
            workSheet.Cell("C1").Value = "Nome";
            workSheet.Cell("D1").Value = "Quantita'";            

            var rngTable = workSheet.Range("A1:D1");

            rngTable.Style
                .Font.SetBold()
                .Fill.SetBackgroundColor(XLColor.CornflowerBlue)
                .Alignment.SetHorizontal(XLAlignmentHorizontalValues.Center);

            rngTable.SetAutoFilter();

            var components =
                _entities.Components.Where(c => !c.Deleted && c.StockQuantity > 0)
                    .OrderBy(c => c.Sku)
                    .Select(c => new {c.Id, c.Sku, c.Name, c.StockQuantity})
                    .ToList();

            workSheet.Cell(2, 1).Value = components.AsEnumerable();

            workSheet.Columns().AdjustToContents();

            var reportStream = new MemoryStream();
            workbook.SaveAs(reportStream);

            return File(reportStream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                        string.Format("Componenti-{0}.xlsx", DateTime.Now.ToString("yyyyMMddHHmm")));
        }

        public ActionResult Create()
        {
            return View(new ComponentCreateModel());
        }

        public PartialViewResult Edit(int componentId)
        {
            var component = _entities.Components.Find(componentId);

            var model = new ComponentEditModel { Id = component.Id, Name = component.Name, Sku = component.Sku };

            return PartialView("_Edit", model);
        }

        public PartialViewResult AddRemoveQuantity(int componentId)
        {
            var component = _entities.Components.Find(componentId);

            var model = new ComponentAddRemoveQuantityModel {Id = component.Id, Name = component.Name, Sku = component.Sku};

            return PartialView("_AddRemoveQuantity", model);
        }

        public PartialViewResult DeleteConfirm(int id)
        {
            var component = _entities.Components.Find(id);

            ViewBag.Id = component.Id;
            ViewBag.ComponentName = component.Name;

            return PartialView("_DeleteConfirm");
        }

        [HttpPost]
        public ActionResult AddRemoveQuantity(ComponentAddRemoveQuantityModel componentAddRemoveQuantityModel)
        {
            var component = _entities.Components.Find(componentAddRemoveQuantityModel.Id);
            component.StockQuantity += decimal.Parse(componentAddRemoveQuantityModel.Quantity);
            component.UpdatedOn = DateTime.Now;

            var componentEntry = new ComponentEntry
            {
                Component = component,
                CreatedOn = DateTime.Now,
                Quantity = decimal.Parse(componentAddRemoveQuantityModel.Quantity),
                Note = componentAddRemoveQuantityModel.Note
            };

            _entities.ComponentEntries.Add(componentEntry);

            _entities.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Create(ComponentCreateModel componentCreateModel)
        {
            if (!ModelState.IsValid)
            {
                return View(componentCreateModel);
            }

            var component = new Component
            {
                CreatedOn = DateTime.Now,
                UpdatedOn = DateTime.Now,
                Name = componentCreateModel.Name,
                Sku = componentCreateModel.Sku
            };

            _entities.Components.Add(component);

            _entities.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpPost]
        public ActionResult Edit(ComponentEditModel componentEditModel)
        {
            var component = _entities.Components.Find(componentEditModel.Id);

            component.Name = componentEditModel.Name;
            component.Sku = componentEditModel.Sku;
            component.Deleted = componentEditModel.Deleted;

            _entities.SaveChanges();

            return RedirectToAction("Index");
        }

        [HttpPost]
        public JsonResult IsValidSku(string sku, int id = 0)
        {
            var componentsCount = id == 0
                ? _entities.Components.Count(c => !c.Deleted && c.Sku == sku)
                : _entities.Components.Count(c => !c.Deleted && c.Sku == sku && c.Id != id);

            return Json(componentsCount == 0);
        }

        [HttpPost]
        public ActionResult Delete(int id)
        {
            var component = _entities.Components.Find(id);

            component.Deleted = true;

            _entities.SaveChanges();

            return RedirectToAction("Index");
        }        
    }    
}

LMT.Web.Application/Views/ComponentGroups/CheckAvailability.cshtml
@model LMT.Web.Application.Models.CheckComponentsAvaiabilityModel

@{
    ViewBag.Title = "Verifica disponibilita' magazzino";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Header
{
    @Html.ActionLink("Esci", "LogOff", "Account", null, new { id = "btnExit", data_icon = "delete", data_ajax = "false", @class = "ui-btn-left" })
    @Html.ActionLink("Home", "Index", "Home", null, new { id = "btnHome", data_icon = "home", data_ajax = "false", @class = "dontprint ui-btn-left", style = "width:100px;margin-left:80px" })
    @Html.ActionLink("Componenti", "Index", "Components", null, new { id = "btnComponents", data_icon = "home", data_theme = "a", data_ajax = "false", @class = "ui-btn-left", style = "width:130px;margin-left:190px" })
    @Html.ActionLink("Assemblati", "Index", "ComponentGroups", null, new { id = "btnComponentGroup", data_icon = "home", data_theme = "a", data_ajax = "false", @class = "ui-btn-left", style = "width:130px;margin-left:330px" })
    <h1>Verifica disponibilita' magazzino</h1>
    <a id="btnPrint" href="#" data-role="button" data-theme="a" class="ui-btn-right" onclick="window.print()">Stampa</a>
}

@section scripts
{
    <script type="text/javascript" src="@(Url.Content("~/Scripts/viewModels/checkViewModel.js"))"></script>
    <script type="text/javascript">

        var lmt = lmt || {};

        $(document).on('pagecreate', function () {

            var componentsAddress = '@Url.Action("GetComponentGroups", "ComponentGroups", new { Area = "" })';
            var checkAvailabilityAddress = '@Url.Action("CalculateAvailability", "ComponentGroups", new { Area = "" })';
            var removeQuantitiesAddress = '@Url.Action("RemoveComponentQuantities", "ComponentGroups", new { Area = "" })';

            var viewModel = new lmt.CheckViewModel(
                {
                    componentsAddress: componentsAddress,
                    checkAvailabilityAddress: checkAvailabilityAddress,
                    removeQuantitiesAddress: removeQuantitiesAddress
                });

            viewModel.initialize();

            //this hack needs while showing dialog
            var vm = ko.dataFor(document.getElementById('ctrlCheck'));

            if (vm === undefined)
                ko.applyBindings(viewModel);
        });
    </script>
}
<style>
    .ui-field-contain .ui-select {
        width: 80%;
    }

    table.grid {
        border-bottom: 1px solid black;
        border-left: 1px solid black;
        width: 100%;
        border-spacing: 0;
    }

    tr:nth-child(odd) {
        background: #FFF;
    }

    td, th {
        border-top: 1px solid black;
        border-right: 1px solid black;
        padding-left: 10px;
    }
</style>
<style type="text/css" media="print">
    .dontprint, #btnExit, #btnHome, #btnComponents, #btnComponentGroup, #btnPrint, #btnRemoveQuantities {
        display: none;
    }
</style>
<ul data-role="listview" data-inset="true" id="ctrlCheck">
    <li data-role="fieldcontain">
        <div data-role="navbar" data-bind="foreach: {data: componentGroupElements, afterRender: onComplete}">
            <ul>
                <li>
                    <select data-role="none" data-bind="foreach: $root.componentGroups, value: selectedComponentGroupId">
                        <option data-bind="attr: { value: value }, text: text"></option>
                    </select>
                </li>
                <li class="ui-field-contain">
                    <input data-bind="value: quantity" type="text" placeholder="Quantita'" />
                </li>
            </ul>
        </div><!-- /navbar -->
        @*<div class="ui-grid-a" data-bind="foreach: componentGroupElements">
                <div class="ui-block-a" style="text-align: center">
                    <select data-role="none" data-bind="foreach: $root.componentGroups, value: selectedComponentGroupId">
                        <option data-bind="attr: { value: value }, text: text"></option>
                    </select>
                </div>
                <div class="ui-block-b" style="text-align: center">

                </div>
            </div>*@
    </li>
    <li data-role="fieldcontain">
        <div class="ui-grid-a">
            <a class="dontprint" data-role="button" href="#" data-bind="click: addComponentGroupElement">Aggiungi assemblato</a>
        </div>
        <div class="ui-grid-b">
            <a class="dontprint" data-role="button" href="#" data-bind="click: calculateAvailability">Calcola residuo magazzino</a>
        </div>
    </li>
</ul>

<div data-role="navbar">
    <ul>
        <li data-bind="visible: componentsRemainingAvailability().length > 0">
            <table class="grid" style="text-align: center">
                <thead>
                    <tr>
                        <th>Codice</th>
                        <th>Descrizione</th>
                        <th>Disponibilita' attuale</th>
                        <th>Disponibilita' necessaria <a id="btnRemoveQuantities" class="ui-btn ui-btn-inline ui-mini" data-rel="dialog" data-inline="true" href="@(Url.Action("RemoveComponentQuantities", "ComponentGroups"))">Scarica</a></th>
                        <th>Disponibilita' residua</th>
                    </tr>
                </thead>
                <tbody data-bind="foreach: componentsRemainingAvailability">
                    <tr class="gridrow">
                        <td data-bind="text: $root.componentsCurrentAvailability()[$index()].Sku"></td>
                        <td data-bind="text: $root.componentsCurrentAvailability()[$index()].Name"></td>
                        <td data-bind="text: $root.componentsCurrentAvailability()[$index()].StockQuantity"></td>
                        <td data-bind="text: $root.componentsNeedAvailability()[$index()].StockQuantity"></td>
                        <td data-bind="text: $root.componentsRemainingAvailability()[$index()].StockQuantity, style: { 'color': StockQuantity > 0 ? 'black' : 'red', 'font-weight': 'bold' }"></td>
                    </tr>
                </tbody>
            </table>
        </li>
    </ul>
</div>

LMT.Web.Application/Views/ComponentGroups/Create.cshtml
@model LMT.Web.Application.Models.ComponentGroupCreateModel

@{
    ViewBag.Title = "Nuovo assemblato";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Header
{
    @Html.ActionLink("Esci", "LogOff", "Account", null, new { data_icon = "delete", @class = "ui-btn-left" })
    @Html.ActionLink("Home", "Index", "Home", null, new { data_icon = "home", @class = "ui-btn-left", style = "width:100px;margin-left:80px" })
    <h1>@ViewBag.Title</h1>
    @Html.ActionLink("Lista assemblati", "Index", "ComponentGroups", new { Area = "" }, new { data_icon = "home", @class = "ui-btn-right" })
}

@using (Html.BeginForm("Create", "ComponentGroups", FormMethod.Post, new { id = "frmCreateComponentGroup" }))
{
    @Html.ValidationSummary(true)

    <ul data-role="listview" data-inset="true">
        <li data-role="list-divider">Nuovo assemblato</li>
        <li data-role="fieldcontain">
            <div class="ui-grid-a">
                @Html.TextBoxFor(model => model.Name, new { placeholder = "Nome componente", style = "width: 95%" })
                @Html.ValidationMessageFor(model => model.Name)
            </div>
        </li>
        <li data-role="fieldcontain">
            <input type="submit" value="Salva" />
        </li>
    </ul>
}

LMT.Web.Application/Views/ComponentGroups/Edit.cshtml
@using Microsoft.Web.Mvc.Html
@model LMT.Web.Application.Models.ComponentGroupEditModel

@{
    ViewBag.Title = "Modifica assemblato";
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section Header
{
    @Html.ActionLink("Esci", "LogOff", "Account", null, new { data_icon = "delete", data_ajax = "false", @class = "ui-btn-left" })
    @Html.ActionLink("Home", "Index", "Home", null, new { data_icon = "home", data_ajax = "false", @class = "ui-btn-left", style = "width:100px;margin-left:80px" })
    @Html.ActionLink("Componenti", "Index", "Components", null, new { data_icon = "home", data_theme = "a", data_ajax = "false", @class = "ui-btn-left", style = "width:130px;margin-left:190px" })
    @Html.ActionLink("Assemblati", "Index", "ComponentGroups", null, new { data_icon = "home", data_theme = "b", data_ajax = "false", @class = "ui-btn-left", style = "width:130px;margin-left:330px" })
    <h1>Modifica assemblato</h1>
}

@section scripts
{
    <script type="text/javascript">
        $(function () {
            var lastItemAddedIndex = @(Model.ComponentGroupComponentModels.Count() - 1);

            $(document).on('click', '#btnAddItem', function () {
                lastItemAddedIndex += 1;
                var ctrlRow = $('li[data-itemrow=' + lastItemAddedIndex + ']');
                $(ctrlRow).show();

                $("input", ctrlRow).trigger("focus");
            });

            $('#btnDeleteComponentGroup').on('click', function () {

                $('input[type="hidden"][name="Deleted"]').val("True");

                $('#frmEditComponentGroup').submit();

                return false;
            });
        });
    </script>
}
@using (Html.BeginForm("Edit", "ComponentGroups", FormMethod.Post, new { id = "frmEditComponentGroup", data_ajax = "false" }))
{
    @Html.ValidationSummary(true)

    @Html.HiddenFor(m => m.Id)
    @Html.HiddenFor(m => m.Deleted)



    <h3>Modifica assemblato</h3>
    <div data-role="navbar">
        <ul>
            <li>

                @Html.TextBoxFor(model => model.Name, new { placeholder = "Nome componente", style = "width: 95%" })
                @Html.ValidationMessageFor(model => model.Name)

            </li>
        </ul>
    </div>
    for (int i = 0; i < Model.ComponentGroupComponentModels.Count(); i++)
    {
        <div data-role="navbar">
            <ul>
                <li>
                    @Html.DropDownListFor(m => m.ComponentGroupComponentModels[i].ComponentId, Model.GetComponents(Model.ComponentGroupComponentModels[i].ComponentId))
                </li>
                <li>
                    @Html.TextBoxFor(m => m.ComponentGroupComponentModels[i].Quantity, new { placeholder = "Quantita'", style = "text-align: center;width: 35%", autocomplete = "off" })
                    @Html.ValidationMessageFor(m => m.ComponentGroupComponentModels[i].Quantity)
                </li>
            </ul>
        </div>
    }
    for (int i = Model.ComponentGroupComponentModels.Count(); i < 50; i++)
    {
        <div data-role="navbar">
            <ul>
                <li data-itemrow="@(i)" style="display: none">
                    @Html.DropDownList(string.Format("ComponentGroupComponentModels[{0}].ComponentId", i), Model.Components)
                </li>
                <li data-itemrow="@(i)" style="display: none">
                    <input style="text-align: center;width:35%" data-val="true" data-val-number="The field Quantity must be a number." placeholder="Quantita'" autocomplete="off"
                           data-val-regex="Formato non valido" data-val-regex-pattern="^-?(([1-9]\d*)|0)(.0*[1-9](0*[1-9])*)?$"
                           data-val-required="The Quantity field is required."
                           id="ComponentGroupComponentModels_@(i)__Quantity" name="ComponentGroupComponentModels[@(i)].Quantity"
                           type="text" value="" class="ui-input-text ui-body-b ui-corner-all ui-shadow-inset">
                    <div style="clear: both"></div>
                    <span class="field-validation-valid" data-valmsg-for="@(string.Format("ComponentGroupComponentModels[{0}].Quantity", i))" data-valmsg-replace="true"></span>
                </li>
            </ul>
        </div>
    }

    <div data-role="navbar">
        <ul>
            <li>
                <input type="button" value="Aggiungi componente" data-mini="true" data-theme="b" id="btnAddItem" />
                <div class="ui-helper-clearfix" style="height: 10px"></div>
                <a href="@(Url.Action("DeleteConfirm", "ComponentGroups", new { id = Model.Id }))" data-role="button" data-rel="dialog" data-ajax="true">Elimina</a>
                <div class="ui-helper-clearfix" style="height: 10px"></div>
                <input type="submit" value="Salva" data-ajax="false" />
            </li>
        </ul>
    </div>
}

LMT.Web.Application/Views/ComponentGroups/_DeleteConfirm.cshtml
<html>
<head></head>
<body>
    <div data-role="dialog">
        <div data-role="header" data-theme="d">
            <h1 style="width: 210px">Elimina assemblato</h1>
        </div>
        <div data-role="content" data-theme="c">
            @using (Html.BeginForm("Delete", "ComponentGroups", FormMethod.Post, new { data_ajax="false" }))
            {
                <input type="hidden" name="Id" value="@(ViewBag.Id)"/>                               
                
                <ul data-role="listview" data-inset="true">
                    <li data-role="fieldcontain">
                        <div class="ui-grid-a" style="text-align: center">
                            Conferma l'eliminazione dell'assemblato @(ViewBag.ComponentGroupName)
                        </div>
                        <div class="ui-grid-b">
                            <input data-ajax="false" type="submit" value="Si" />                           
                        </div>
                        <div class="ui-grid-c">
                            <a data-role="button" data-rel="back" id="btnAbort" data-ajax="false" href="#">Annulla</a>
                        </div>
                    </li>                    
                </ul>
            }            
        </div>
    </div>
</body>
</html>