LMT.Web.Application/Controllers/MaintenanceController.cs
using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Web.Mvc;
using LMT.Data.EF;
using System.Linq;
using LMT.Web.Application.Models;
using LMT.Web.Application.Properties;
using MvcContrib.Pagination;
using ClosedXML.Excel;

namespace LMT.Web.Application.Controllers
{
    [Authorize]
    public class MaintenanceController : Controller
    {
        private readonly Entities _entities;

        public MaintenanceController()
        {
            _entities = new Entities();
        }

        public ActionResult Index(int? page, string searchTerms, bool? searchEnabledStatus, MaintenanceSearchModel maintenanceSearchModel)
        {
            var maintenances = GetMaintenances(maintenanceSearchModel);            

            var maintenanceStates =
                _entities.MaintenanceStates.OrderBy(m => m.DisplayOrder).Select(
                    m => new SelectListItem { Text = m.Name, Value = m.Code }).ToList();

            var maintenanceReadModels =
                maintenances.ToList().OrderByDescending(m => m.UpdateDate).Select(
                    m =>
                    new MaintenanceReadModel
                        {
                            Id = m.Id,
                            UpdatedOn = m.UpdateDate.ToString(CultureInfo.InvariantCulture),
                            CreationDate = m.CreationDate.ToString(CultureInfo.InvariantCulture),
                            CustomerName = m.CustomerName,
                            ModelNumber = m.ModelNumber,
                            BrandName = m.BrandName,
                            Sku = m.ProductSku,
                            State = m.MaintenanceState.Name
                        });

            maintenanceSearchModel.SearchResultModels = maintenanceReadModels.AsPagination(page ?? 1, 15);
            maintenanceSearchModel.MaintenanceStates = maintenanceStates;

            return View(maintenanceSearchModel);
        }

        public FileContentResult SearchExport(MaintenanceSearchModel maintenanceSearchModel)
        {
            var workbook = new XLWorkbook(new MemoryStream(Resources.ReportSearchExportTemplate));
            var workSheet = workbook.Worksheets.First();

            workSheet.Column("1").Hide();
            workSheet.Cell("A1").Value = "Id";
            workSheet.Cell("B1").Value = "Data";
            workSheet.Cell("C1").Value = "Cliente";            
            workSheet.Cell("D1").Value = "Marca";
            workSheet.Cell("E1").Value = "Modello";
            workSheet.Cell("F1").Value = "Matricola";
            workSheet.Cell("G1").Value = "Stato";            

            var rngTable = workSheet.Range("A1:G1");

            rngTable.Style
                .Font.SetBold()
                .Fill.SetBackgroundColor(XLColor.CornflowerBlue)
                .Alignment.SetHorizontal(XLAlignmentHorizontalValues.Center);

            rngTable.SetAutoFilter();

            var maintenances = GetMaintenances(maintenanceSearchModel);

            var maintenanceModels =
                maintenances.ToList().OrderByDescending(m => m.CreationDate).Select(
                    m =>
                    new
                        {
                            m.Id,
                            CreationDate = m.CreationDate.ToString(CultureInfo.InvariantCulture),
                            m.CustomerName,                            
                            m.BrandName,
                            m.ModelNumber,
                            Sku = m.ProductSku,
                            State = m.MaintenanceState.Name
                        });

            workSheet.Cell(2, 1).Value = maintenanceModels.AsEnumerable();

            workSheet.Columns().AdjustToContents();

            var reportStream = new MemoryStream();
            workbook.SaveAs(reportStream);

            return File(reportStream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                        string.Format("Riparazioni-{0}.xlsx", DateTime.Now.ToString("yyyyMMddHHmm")));
        }
        
        public FileContentResult DetailExport(int maintenanceId)
        {
            var maintenance = _entities.Maintenances.Find(maintenanceId);

            var workbook = new XLWorkbook(new MemoryStream(Resources.MaintenanceTemplate));
            var workSheet = workbook.Worksheets.First();
            
            workSheet.Cell("E5").Value = maintenance.CreationDate;
            workSheet.Cell("E6").Value = maintenance.CustomerName;
            workSheet.Cell("E7").Value = !string.IsNullOrWhiteSpace(maintenance.BrandName) ? maintenance.BrandName : "-";
            workSheet.Cell("E8").Value = !string.IsNullOrWhiteSpace(maintenance.ModelNumber) ? maintenance.ModelNumber : "-";
            workSheet.Cell("E9").Value = !string.IsNullOrWhiteSpace(maintenance.ProductSku) ? maintenance.ProductSku : "-"; ;

            for (int i = 0; i < maintenance.MaintenanceItems.Count(); i++)
            {
                var maintenanceItem = maintenance.MaintenanceItems.ElementAt(i);
                workSheet.Cell("A" + (20 + i)).Value = maintenanceItem.Description;
                workSheet.Cell("F" + (20 + i)).Value = maintenanceItem.Price.ToString("#.00");
            }

            workSheet.Cell("A39").Value = string.Format("Manodopera - {0}", maintenance.HandWorkHours);
            workSheet.Cell("F39").Value = maintenance.HandWorkPrice;

            var totalPrice = maintenance.MaintenanceItems.Select(m => m.Price).Sum() + maintenance.HandWorkPrice;

            workSheet.Cell("F40").Value = totalPrice;

            var reportStream = new MemoryStream();
            workbook.SaveAs(reportStream);

            return File(reportStream.ToArray(), "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet",
                        string.Format("Riparazione-{0}.xlsx", DateTime.Now.ToString("yyyyMMddHHmm")));
        }

        public ActionResult Create()
        {
            var maintenanceStates =
                _entities.MaintenanceStates.OrderBy(m => m.DisplayOrder).Select(
                    m => new SelectListItem {Text = m.Name, Value = m.Code}).ToList();

            var model = new MaintenanceCreateModel { CreationDate = DateTime.Now.ToString("dd-MM-yyyy"), MaintenanceStates = maintenanceStates };

            return View(model);
        }

        public ActionResult Edit(int id)
        {
            var maintenance = _entities.Maintenances.Find(id);

            var model = GetMaintenanceEditModel(maintenance);
            
            if (Request.UrlReferrer != null) 
                model.ReturningUrl = Request.UrlReferrer.OriginalString;

            return View(model);
        }

        [HttpPost]
        public ActionResult Create(MaintenanceCreateModel maintenanceCreateModel)
        {
            if(!ModelState.IsValid)
            {
                var maintenanceStates =
                   _entities.MaintenanceStates.Select(m => new SelectListItem { Text = m.Name, Value = m.Code }).ToList();

                maintenanceCreateModel.MaintenanceStates = maintenanceStates;

                return View(maintenanceCreateModel);
            }

            var selectedMaintenanceStateCode = maintenanceCreateModel.SelectedMaintenanceState.Value.ToString(CultureInfo.InvariantCulture);
            var maintenanceState =
                _entities.MaintenanceStates.First(
                    m => m.Code == selectedMaintenanceStateCode);

            var maintenance = new Maintenance
                                  {
                                      BrandName = maintenanceCreateModel.BrandName,
                                      CreationDate = DateTime.Now,
                                      UpdateDate = DateTime.Now,
                                      CustomerName = maintenanceCreateModel.Customer,
                                      MaintenanceState =
                                          maintenanceState,
                                      ModelNumber = maintenanceCreateModel.Model,
                                      ProductSku = maintenanceCreateModel.Sku,
                                      HandWorkHours = maintenanceCreateModel.HandWorkHours,
                                      HandWorkPrice =
                                          decimal.Parse(string.IsNullOrWhiteSpace(maintenanceCreateModel.HandWorkPrice)
                                                            ? "0"
                                                            : maintenanceCreateModel.HandWorkPrice)
                                  };

            foreach (var maintenanceItemModel in maintenanceCreateModel.MaintenanceItemModels)
            {
                var price =
                    decimal.Parse(string.IsNullOrWhiteSpace(maintenanceItemModel.MaintenancePrice)
                                      ? "0"
                                      : maintenanceItemModel.MaintenancePrice);

                if(string.IsNullOrWhiteSpace(maintenanceItemModel.MaintenanceDescription) && price == 0)
                    continue;

                var maintenanceItem = new MaintenanceItem
                                          {
                                              Description = maintenanceItemModel.MaintenanceDescription ?? "-",
                                              Price = price,
                                              Maintenance = maintenance
                                          };

                maintenance.MaintenanceItems.Add(maintenanceItem);
            }

            _entities.Maintenances.Add(maintenance);
            _entities.SaveChanges();

            return RedirectToAction("Index");

LMT.Web.Application/Views/Maintenance/Create.cshtml
@model LMT.Web.Application.Models.MaintenanceCreateModel
@{
    ViewBag.Title = "Riparazioni";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
@section Header
{
    @Html.ActionLink("Esci", "LogOff", "Account", null, new { data_icon = "delete", @class = "ui-btn-left" })
    @Html.ActionLink("Home", "Index", "Home", null, new { data_icon = "home", @class = "ui-btn-left", style = "width:100px;margin-left:80px" })
    <h1>@ViewBag.Title</h1>
    @Html.ActionLink("Lista riparazioni", "Index", "Maintenance", new { Area = "" }, new { data_icon = "new", @class = "ui-btn-right" })
}
@section scripts
{
    <script type="text/javascript">
        $(document).bind('pagechange', function () {

            var ctrlItemDescription = $('textarea', 'div[class="ui-block-a"]');
            ctrlItemDescription.height(22);

            var ctrlItemPrices = $('input[data-item-price], input[data-item-handwork]');
            var ctrlGridContainer = $('div[class="ui-bar ui-bar-a"]', 'div[class="ui-block-b"]');

            //ctrlItemPrice.height(ctrlGridContainer.height() + 1);

            $('input', ctrlItemPrices).blur(function () {

                var price = $(this).val();
                price = price === "" ? 0 : price;

                $(this).val(parseFloat(price).toFixed(2));
            });

            $('input', $('div[class="ui-bar ui-bar-a"]', 'div[class="ui-block-c"]')).blur(function () {

                var price = $(this).val();
                price = price === "" ? 0 : price;

                $(this).val(parseFloat(price).toFixed(2));
            });

            $(document).on('keyup', ctrlItemPrices, function () {
                var lblTotal = $('#lblTotal');

                var sum = 0;
                $(ctrlItemPrices).each(function () {
                    sum += Number($(this).val());
                }).promise().done(function () {
                    
                    lblTotal.text("€ " + parseFloat(sum).toFixed(2));
                });
            });

            var lastItemAddedId = 0;

            $(document).on('click', '#btnAddItem', function () {
                lastItemAddedId += 1;
                var ctrlRow = $('div[data-itemrow=' + lastItemAddedId + ']');
                $(ctrlRow).show();
                $('textarea', ctrlRow).focus();
            });

            $('#Customer').focus();


            window.onbeforeunload = function () {
                return "Si sta tentando di uscire da questa pagina. Se sono state apportate modifiche ai campi senza fare clic sul pulsante Salva, le modifiche andranno perse. Sei sicuro di voler uscire da questa pagina?";
            };

            $('#frmCreateMaintenance').submit(function (sender, isValidSubmit) {

                if (!$('#frmCreateMaintenance').valid())
                    return false;

                if (isValidSubmit)
                    return true;

                window.onbeforeunload = function () { };

                $('<div>').simpledialog2({
                    mode: 'button',
                    headerText: 'Creare una nuova riparazione?',
                    headerClose: true,
                    buttonPrompt: 'Scegliendo "Si" verrà creata una nuova riparazione',
                    buttons: {
                        'Si': {
                            click: function () {
                                $('#frmCreateMaintenance').trigger('submit', [{ isValidSubmit: true}]);
                            }
                        },
                        'No': {
                            click: function () {

                            },
                            icon: "delete",
                            theme: "c"
                        }
                    }
                });

                return false;
            });

        });
    </script>
}
@using (Html.BeginForm("Create", "Maintenance", FormMethod.Post, new { id = "frmCreateMaintenance" }))
{
    @Html.ValidationSummary(true)

    <ul data-role="listview" data-inset="true">
        <li data-role="list-divider">Nuova riparazione</li>
        <li data-role="fieldcontain">
            <div class="ui-grid-a">
                <div class="ui-block-a">
                    <input value="@(Model.CreationDate)" name="CreationDate" placeholder="Data" style="width:95%" data-role="datebox" data-options='{"mode": "calbox", "useNewStyle": true, "useFocus": true}'/>
                </div>
                <div class="ui-block-b">
                    @Html.TextBoxFor(m => m.Customer, new { placeholder = "Azienda", style = "width:95%;" })
                    @Html.ValidationMessageFor(m => m.Customer)
                </div>
            </div>
        </li>
        <li data-role="fieldcontain">
            <div class="ui-grid-a">
                <div class="ui-block-a">
                    @Html.TextBoxFor(m => m.BrandName, new { placeholder = "Marca", style = "width:95%;" })
                    @Html.ValidationMessageFor(m => m.BrandName)
                </div>
                <div class="ui-block-b">
                    @Html.TextBoxFor(m => m.Model, new { placeholder = "Modello", style = "width:95%;" })
                </div>
            </div>
        </li>
        <li data-role="fieldcontain">
            <div class="ui-grid-a">
                <div class="ui-block-a">
                    @Html.TextBoxFor(m => m.Sku, new { placeholder = "Matricola", style = "width:95%;" })
                </div>
                <div class="ui-block-b">
                    <fieldset data-role="controlgroup" data-mini="true" data-type="horizontal" data-theme="a">
                        @for (var i = 0; i < Model.MaintenanceStates.Count(); i++)
                        {
                            <input type="radio" name="SelectedMaintenanceState" id='MaintenanceStates[@(i)].Value' value="@(Model.MaintenanceStates[i].Value)" data-theme="c" />
                            <label for='MaintenanceStates[@(i)].Value'>
                                @(Model.MaintenanceStates[i].Text)</label>
                        }
                        <div style="clear: both">
                        </div>
                        @Html.ValidationMessageFor(m => m.SelectedMaintenanceState, "", new { style = "text-align: left" })
                    </fieldset>
                </div>
            </div>
        </li>
        <li data-role="fieldcontain">
            <div class="ui-grid-a" style="height: 30px" data-theme="a">
                <div class="ui-block-a" style="width: 70%">
                    <div class="ui-bar ui-bar-a">
                        <strong>Descrizione</strong></div>
                </div>
                <div class="ui-block-b" style="width: 30%">
                    <div class="ui-bar ui-bar-a">
                        <strong>Prezzo</strong></div>
                </div>
            </div>
            @for (int i = 0; i < 15; i++)
            {
                <div class="ui-grid-a" data-theme="a" style='display: @(i == 0 ? "block" : "none")' data-itemrow="@(i)">
                    <div class="ui-block-a" style="width: 70%">
                        <div class="ui-bar ui-bar-a">
                            @Html.TextAreaFor(m => m.MaintenanceItemModels[i].MaintenanceDescription, new { placeholder = "Descrizione", style = "width:98%;" })
                            @Html.ValidationMessageFor(m => m.MaintenanceItemModels[i].MaintenanceDescription)
                        </div>
                    </div>
                    <div class="ui-block-b" style="width: 30%">
                        <div class="ui-bar ui-bar-a">
                            @Html.TextBoxFor(m => m.MaintenanceItemModels[i].MaintenancePrice, new { placeholder = "Prezzo (es. 10.5)", style = "width:98%;text-align:right", autocomplete = "off", data_item_price = "" })
                            @Html.ValidationMessageFor(m => m.MaintenanceItemModels[i].MaintenancePrice)
                        </div>
                    </div>
                </div>
            }
            <input type="button" value="Aggiungi voce" data-mini="true" data-theme="a" id="btnAddItem" />
            <div style="clear: both; height: 10px">
            </div>
            <div class="ui-grid-b" data-theme="a" style="height: 75px">
                <div class="ui-block-a" style="width: 40%">
                    <div class="ui-bar ui-bar-a" style="height: 75px">
                        @Html.Label("Mano d'opera", new { style = "width:98%" })
                    </div>
                </div>
                <div class="ui-block-b" style="width: 30%">
                    <div class="ui-bar ui-bar-a" style="height: 75px">
                        @Html.TextBoxFor(m => m.HandWorkHours, new { placeholder = "Ore (es. 4 + 1/2)", style = "width:98%;text-align:right", autocomplete = "off" })
                        @Html.ValidationMessageFor(m => m.HandWorkHours)
                    </div>
                </div>
                <div class="ui-block-c" style="width: 30%">
                    <div class="ui-bar ui-bar-a" style="height: 65px">
                        @Html.TextBoxFor(m => m.HandWorkPrice, new { placeholder = "Prezzo (es. 10.5)", style = "width:98%;text-align:right", autocomplete = "off", data_item_handwork = "" })
                        @Html.ValidationMessageFor(m => m.HandWorkPrice)
                    </div>
                </div>
            </div>
            <div class="ui-grid-a" style="height: 30px" data-theme="a">
                <div class="ui-block-a" style="width: 70%;">
                    <div class="ui-bar ui-bar-a" style="text-align: right;">
                        <strong>Totale + IVA</strong>
                    </div>
                </div>
                <div class="ui-block-b" style="width: 30%;">
                    <div class="ui-bar ui-bar-a" style="text-align: right;">
                        <strong><span id="lblTotal">€ 0</span></strong></div>
                </div>
            </div>
        </li>
        <li data-role="fieldcontain">
            <input type="submit" value="Salva" />
        </li>
    </ul>
}

LMT.Web.Application/Views/Maintenance/Index.cshtml
@using MvcContrib.Pagination
@using MvcContrib.UI.Grid
@using MvcContrib.UI.Pager
@model LMT.Web.Application.Models.MaintenanceSearchModel
@{
    ViewBag.Title = "Riparazioni";
    Layout = "~/Views/Shared/_Layout.cshtml";
}
<style>
    tr.gridrow {
    }

    table.grid {
        border-bottom: 1px solid black;
        border-left: 1px solid black;
        width: 100%;
        border-spacing: 0;
    }

    td, th {
        border-top: 1px solid black;
        border-right: 1px solid black;
        padding-left: 10px;
    }

    tr:nth-child(odd) {
        background: #FFF;
    }

    tr:nth-child(even) {
        background: #AAA;
    }

    div.pager {
        text-align: center;
        margin: 5px;
    }
</style>
@section Header
{
    @Html.ActionLink("Esci", "LogOff", "Account", null, new { data_icon = "delete", @class = "ui-btn-left" })
    @Html.ActionLink("Home", "Index", "Home", null, new { data_icon = "home", @class = "ui-btn-left", style = "width:100px;margin-left:80px" })
    <h1>@ViewBag.Title</h1>
    @Html.ActionLink("Nuova riparazione", "Create", "Maintenance", new { Area = "" }, new { @class = "ui-btn-right ui-icon-plus", data_icon = "plus" })
}
@section scripts
{
    <script type="text/javascript">
        $(document).bind('pageinit', function () {

            var links = $('a').filter(function () { return $(this).text() === "avanti" || $(this).text() === "ultimo" || $(this).text() === "primo" || $(this).text() === "indietro"; });

            links.removeClass("ui-btn");

            @if (!string.IsNullOrWhiteSpace(Model.SelectedMaintenanceState))
            {
                <text>
            $('input[type="radio"][value=@(Model.SelectedMaintenanceState)]').attr("checked", true).checkboxradio("refresh");
            </text>
            }

            $(document).on('click', '#btnSearchExport', function () {
                var exportUrl = '@(Url.Action("SearchExport", "Maintenance", new { Area = "" }))';

                var form = $('#frmSearch');
                form.attr('action', exportUrl);
                form.submit();

                return false;
            });

            $(document).on('click', '#btnSearch', function () {
                var searchUrl = '@(Url.Action("Index", "Maintenance", new { Area = "" }))';

                var form = $('#frmSearch');
                form.attr('action', searchUrl);
                form.submit();

                return false;
            });
        });
    </script>
}
@using (Html.BeginForm("Index", "Maintenance", FormMethod.Get, new { id = "frmSearch" }))
{    
    <ul data-role="listview" data-inset="true">
        <li data-role="list-divider">
            <div>
                <span>Ricerca</span>
                @Html.ActionLink("Reset", "Index", "Maintenance", new {}, new { Area = "", style = "float:right;", data_theme="b" })
            </div>
        </li>
        <li data-role="fieldcontain">
            <div class="ui-grid-a" style="height: 140px">
                <div class="ui-block-a" style="width: 25%">
                    @Html.TextBoxFor(m => m.StartDate, new { placeholder = "Data inizio", style = "width:90%;", data_role = "datebox", data_options = "{\"mode\": \"calbox\", \"useNewStyle\": true, \"useFocus\": true}" })
                </div>
                <div class="ui-block-b" style="width: 25%">
                    @Html.TextBoxFor(m => m.EndDate, new { placeholder = "Data fine", style = "width:90%;", data_role = "datebox", data_options = "{\"mode\": \"calbox\", \"useNewStyle\": true, \"useFocus\": true}" })
                </div>
                <div class="ui-block-c" style="width: 50%">
                    <div class="ui-bar ui-bar-a">
                        <fieldset data-role="controlgroup" data-mini="true" data-type="horizontal">
                            @for (var i = 0; i < Model.MaintenanceStates.Count(); i++)
                            {
                                <input type="radio" name="SelectedMaintenanceState" id='MaintenanceStates[@(i)].Value' value="@(Model.MaintenanceStates[i].Value)" />
                                <label for='MaintenanceStates[@(i)].Value'>
                                    @(Model.MaintenanceStates[i].Text)
                                </label>
                            }
                        </fieldset>                        
                    </div>
                </div>
            </div>
        </li>
        <li data-role="fieldcontain">
            <div class="ui-block-a" style="width: 20%">
                @Html.TextBoxFor(m => m.CustomerName, new { placeholder = "Cliente", style = "width:90%;" })
            </div>
            <div class="ui-block-b" style="width: 20%">
                @Html.TextBoxFor(m => m.Brand, new { placeholder = "Marca", style = "width:90%;" })
            </div>
            <div class="ui-block-c" style="width: 20%">
                @Html.TextBoxFor(m => m.Model, new { placeholder = "Modello", style = "width:90%;" })
            </div>
            <div class="ui-block-d" style="width: 20%">
                @Html.TextBoxFor(m => m.Sku, new { placeholder = "Matricola", style = "width:90%;" })
            </div>
            <div class="ui-block-e" style="width: 20%;padding-top: 3px">
                <input type="checkbox" name="ExcludeClosedStates" id="ExcludeClosedStates" data-mini="true" data-theme="c" @(Model.ExcludeClosedStates == "on" ? "checked='checked'" : "") />
                <label for="ExcludeClosedStates">Escludi chiusi</label>
            </div>
        </li>
        <li data-role="fieldcontain">
            <input id="btnSearch" type="submit" value="Cerca" data-theme="b" />
        </li>
    </ul>
}

<div data-role="navbar">
    <ul data-inset="true" data-theme="a">
        <li data-role="list-divider">
            <div>
                <span>Riparazioni</span><a href="#" style="float: right; width: 50px;" data-theme="b" id="btnSearchExport">Esporta</a>
            </div>
        </li>        
    </ul>
    <ul>
        <li data-role="fieldcontain">
            @Html.Pager((IPagination)Model.SearchResultModels).First("primo").Last("ultimo").Next("avanti").Previous("indietro").Format("Visualizzati da {0} a {1} | Totale: {2} risultati | ").SingleFormat("")
            <div style="height: 10px">
            </div>
            @Html.Grid(Model.SearchResultModels).Columns(column =>
        {
            column.For(p => p.UpdatedOn).Named("Ultimo aggiornamento").Attributes(style => "width:130px");
            column.For(p => p.CreationDate).Named("Data creazione").Attributes(style => "width:130px");
            column.For(p => p.CustomerName).Named("Cliente").Attributes(style => "width:180px");
            column.For(p => p.BrandName).Named("Marca").Attributes(style => "width:180px");
            column.For(p => p.ModelNumber).Named("Modello").Attributes(style => "width:180px");
            column.For(p => p.Sku).Named("Matricola").Attributes(style => "width:160px");
            column.For(p => p.State).Named("Stato").Attributes(style => "width:150px");

            column.For(m => Html.ActionLink("Modifica", "Edit", "Maintenance", new { id = m.Id }, new { data_role = "button", data_mini = "true" })).Attributes(style => "width:90px;padding-left:5px;padding-right:5px");

        }).Empty("Non sono presenti riparazioni")
            <div style="height: 10px">
            </div>
            @Html.Pager((IPagination)Model.SearchResultModels).First("primo").Last("ultimo").Next("avanti").Previous("indietro").Format("Pagina {0} di {1} | Totale: {2} risultati | ").SingleFormat("")
        </li>
    </ul>

</div>